SELECT * 
FROM RETAIL_SALES


--NULL VALUES DATA CLEANING

SELECT * FROM RETAIL_SALES
WHERE 
	TRANSACTIONS_ID IS NULL
	OR
	SALE_DATE IS NULL
	OR 
	SALE_TIME IS NULL
	OR 
	GENDER IS NULL 
	OR 
	CATEGORY IS NULL
	OR 
	QUANTIY IS NULL
	OR
	COGS IS NULL
	OR 
	TOTAL_SALE IS NULL
	OR 
	PRICE_PER_UNIT IS NULL;


	--DELETE NULL VALUES

	DELETE FROM RETAIL_SALES
	WHERE 
	TRANSACTIONS_ID IS NULL
	OR
	SALE_DATE IS NULL
	OR 
	SALE_TIME IS NULL
	OR 
	GENDER IS NULL 
	OR 
	CATEGORY IS NULL
	OR 
	QUANTIY IS NULL
	OR
	COGS IS NULL
	OR 
	TOTAL_SALE IS NULL
	OR 
	PRICE_PER_UNIT IS NULL;


	--DATA EXPLORATION

	--HOW MANY SALES WE HAVE

	SELECT COUNT(*) AS TOTAL_SALE FROM RETAIL_SALES

	--HOW MANY COUSTOMER WE HAVE

	SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_SALE FROM RETAIL_SALES
	
	SELECT DISTINCT CATEGORY AS TOTAL_SALE FROM RETAIL_SALES

	-- DATA ANALYSIS & BUSINESS KEY PROBLEMS


	--Q1 WRITE A SQL QUERY TO RETRIEVE ALL COLUMNS FOR THE SALES MADE ON '2022-11-05

	SELECT * 
	FROM RETAIL_SALES
	

	--Q2 WRITE A SQL QUERY TO RETRIEVE ALL TRANSACTION WHERE CATEGORY IS  CLOTHING AND QUANTITY SOLD IS MORE THAN 3 IN MONTH OF NOVEMBER

SELECT * 
FROM RETAIL_SALES
WHERE CATEGORY = 'CLOTHING'
  AND FORMAT(SALE_DATE, 'yyyy-MM') = '2022-11'
  AND QUANTIY > 3;


  --Q3 TO CALCULATE TOTAL SALES FOR EACH CATEGORY

SELECT CATEGORY,SUM(TOTAL_SALE) AS NET_SALE,
COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_SALES
GROUP BY CATEGORY;

--Q4 Write a SQL query to find the average age of customers who purchased items from the 'Beauty' category.:

SELECT AVG(AGE) AS AVG_AGE 
FROM RETAIL_SALES
WHERE CATEGORY ='BEAUTY';

SELECT ROUND(COGS,2) FROM RETAIL_SALES


-- Q5 Write a SQL query to find all transactions where the total_sale is greater than 1000.:

SELECT * 
FROM RETAIL_SALES 
WHERE TOTAL_SALE >1000;


 -- Q6.Write a SQL query to find the total number of transactions (transaction_id) made by each gender in each category.:

 SELECT CATEGORY,
 GENDER, COUNT(*) AS TOTAL_TRANS
 FROM RETAIL_SALES 
 GROUP BY
 CATEGORY,
 GENDER
 ORDER BY CATEGORY;

 -- Q7 Write a SQL query to calculate the average sale for each month. Find out best selling month in each year:
SELECT 
    YEAR,
    MONTH,
    AVG_SALE
FROM (
    SELECT 
        YEAR(SALE_DATE) AS YEAR,
        MONTH(SALE_DATE) AS MONTH,
        AVG(TOTAL_SALE) AS AVG_SALE,
        RANK() OVER (
            PARTITION BY YEAR(SALE_DATE)
            ORDER BY AVG(TOTAL_SALE) DESC
        ) AS RANK
    FROM RETAIL_SALES
    GROUP BY YEAR(SALE_DATE), MONTH(SALE_DATE)
) AS T1
WHERE RANK = 1;


--Q8 **Write a SQL query to find the top 5 customers based on the highest total sales **:

SELECT TOP 5
  CUSTOMER_ID,
  SUM(TOTAL_SALE) AS TOTAL_SALES
FROM RETAIL_SALES
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_SALES DESC;

--Q9 Write a SQL query to find the number of unique customers who purchased items from each category.:

SELECT CATEGORY,
COUNT(DISTINCT CUSTOMER_ID) AS CNT_UNIQUE_CS
FROM RETAIL_SALES
GROUP BY CATEGORY

--Q10 Write a SQL query to create each shift and number of orders (Example Morning <12, Afternoon Between 12 & 17, Evening >17):

SELECT 
  CASE 
    WHEN DATEPART(HOUR, SALE_TIME) < 12 THEN 'Morning'
    WHEN DATEPART(HOUR, SALE_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
    ELSE 'Evening'
  END AS SHIFT,
  COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_SALES
GROUP BY 
  CASE 
    WHEN DATEPART(HOUR, SALE_TIME) < 12 THEN 'Morning'
    WHEN DATEPART(HOUR, SALE_TIME) BETWEEN 12 AND 17 THEN 'Afternoon'
    ELSE 'Evening'
  END;